name: Terraform CI

on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Validation and Plan
    runs-on: ubuntu-latest

    env:
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}
      TF_VAR_ssh_source_address: ${{ vars.TF_VAR_SSH_SOURCE_ADDRESS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false